In [ ]:
# numpy basic operation 
#create an array
#creating a 0-d aaray 
#number of elements
#total memory token by as an array
#single element size 
#for the data type of the array
#for the specific element of the array
#specific row of the array 
#start index:ending index, inclusive : exclusive 
#iterating in 1 dimension


In [1]:
import numpy as np

In [2]:
#create an array
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
#creating a 0-d aaray 
arrzero = np.array(80)
print(arrzero)

80


In [8]:
arr.ndim

1

In [18]:
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print (arr2)
print(arr2.ndim)

[[1 2 3 4 5]
 [1 2 3 4 5]]
2


In [19]:
#number of elements
arr2.size

10

In [20]:
#total memory token by as an array
arr2.nbytes

80

In [21]:
arrzero.nbytes

8

In [23]:
#single element size 
arr2.itemsize

8

In [25]:
#for the data type of the array
arr2.dtype

dtype('int64')

In [26]:
print(arr2)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [28]:
#for the specific element of the array()
arr2[0,2]

np.int64(3)

In [29]:
#specific row of the array 
arr2[0,:]

array([1, 2, 3, 4, 5])

In [31]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10])
print (arr3)

[ 1  2  3  4  5  6  7  8  9 10]


In [32]:
#start index:ending index, inclusive : exclusive 
arr3[1:5]

array([2, 3, 4, 5])

In [33]:
arr3[5:]

array([ 6,  7,  8,  9, 10])

In [35]:
print(arr3[:5])

[1 2 3 4 5]


In [36]:
print(arr2)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [37]:
print(arr2[1,1:4])

[2 3 4]


In [40]:
#copying of array 
arr4 = arr2.copy()
print(arr4)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [41]:
#Zero matrix
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [42]:
#All 1 matrix
np.ones((6,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [43]:
#other matrix
np.full((40,40),678)

array([[678, 678, 678, ..., 678, 678, 678],
       [678, 678, 678, ..., 678, 678, 678],
       [678, 678, 678, ..., 678, 678, 678],
       ...,
       [678, 678, 678, ..., 678, 678, 678],
       [678, 678, 678, ..., 678, 678, 678],
       [678, 678, 678, ..., 678, 678, 678]], shape=(40, 40))

In [44]:
#importing random
from numpy import random 

In [46]:
x = random.randint(100)
print(x)

52


In [48]:
#identity matrix 
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
#mathematical operation in array
arrm = np.array([10,20,30,40,50])
print (arrm)


[10 20 30 40 50]


In [50]:
#plus operation
arrm+15

array([25, 35, 45, 55, 65])

In [51]:
arrm

array([10, 20, 30, 40, 50])

In [56]:
#subtraction operation
arm = arrm - 40
print(arrm)


[10 20 30 40 50]


In [57]:
arrz = arrm+100
arrz

array([110, 120, 130, 140, 150])

In [58]:
#multiplication
arrm*10
print(arrm)

[10 20 30 40 50]


In [59]:
#division operation 
arm/7

array([-4.28571429, -2.85714286, -1.42857143,  0.        ,  1.42857143])

In [60]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([10,15,20,25,30])
print(a1+a2)

[11 17 23 29 35]


In [61]:
#cos funtion in an array 
np.cos(a1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [62]:
print(arr2)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [64]:
#minimum value for the array 
np.min(arr2)


np.int64(1)

In [65]:
#mamimum value from the array 
np.max(arr2)

np.int64(5)

In [67]:
np.sum(arr2)
print(arr2)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [68]:
#iterating in 1 dimension
for x in a1:
    print(x)

1
2
3
4
5


In [69]:
#iterating
for a in arr2:
    for b in a:
        print(b)

1
2
3
4
5
1
2
3
4
5
